### ISSUE TITLE
Incorrect API Code Causes Crash

### ISSUE THREAD

**Issue by brousch** [Hanga/hanga-cli#1]
I ran Hanga with an intentionally incorrect API code. Instead of a nice error message I got:

```
C:\Users\ben\Projects\saythis>hanga -v android debug
I Check configuration tokens
I Ensure build layout
Unable to read the state.db, content will be replaced.
D Create directory C:\Users\ben\.buildozer\hanga\platform\hanga\platform
D Create directory .buildozer\hanga\platform
D Create directory .buildozer\hanga\app
I Prepare the source code to pack
D Copy application source from C:\Users\ben\Projects\saythis\saythis
D Create directory C:\Users\ben\Projects\saythis\.buildozer\hanga\app
D Copy C:\Users\ben\Projects\saythis\saythis\main.py
D Copy C:\Users\ben\Projects\saythis\saythis\saythis.kv
D Create directory C:\Users\ben\Projects\saythis\.buildozer\hanga\app\images
D Copy C:\Users\ben\Projects\saythis\saythis\images\background.png
D Create directory C:\Users\ben\Projects\saythis\.buildozer\hanga\app\resources
D Copy C:\Users\ben\Projects\saythis\saythis\resources\highres-icon.png
D Copy C:\Users\ben\Projects\saythis\saythis\resources\icon-114x114.png
D Copy C:\Users\ben\Projects\saythis\saythis\resources\icon.png
D Copy C:\Users\ben\Projects\saythis\saythis\resources\presplash.jpg
D Create directory C:\Users\ben\Projects\saythis\.buildozer\hanga\app\resources\
pinstriped_suit
D Copy C:\Users\ben\Projects\saythis\saythis\resources\pinstriped_suit\pinstripe
d_suit.png
D Copy C:\Users\ben\Projects\saythis\saythis\resources\pinstriped_suit\pinstripe
d_suit_@2X.png
I Compress the application
D Create custom buildozer.spec
I Submit the application to build
I Submitting Say This
Upload [##########################################################]   6.59 kB/s
Traceback (most recent call last):
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\runpy.py", line 162, in _run_modu
le_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\Scripts\hanga.exe\__main__.py", line
9, in <module>
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\site-packages\hanga\scripts\clien
t.py", line 257, in main
    HangaClient().run_command(arguments)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\site-packages\hanga\scripts\clien
t.py", line 95, in run_command
    self.cloud_submit(args, filename)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\site-packages\hanga\scripts\clien
t.py", line 168, in cloud_submit
    result = self._hangaapi.submit(args, filename, submit_callback)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\site-packages\hanga\api.py", line
 55, in submit
    return r.json()
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\site-packages\requests-2.2.1-py2.
7.egg\requests\models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\json\__init__.py", line 338, in l
oads
    return _default_decoder.decode(s)
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\json\decoder.py", line 365, in de
code
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Kivy-1.8.0-py2.7-win32\Python27\lib\json\decoder.py", line 383, in ra
w_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by tito** [comment]
You're right, i should get a better error message
