### ISSUE TITLE
Cannot run android build

### ISSUE THREAD

**Issue by nrbrd** [Hanga/hanga-cli#5]
trying to run
hanga android

I'm missing something?

# Compress the application
# Create custom buildozer.spec
# Submit the application to build
# Submitting Kivy Designer Tabs
Traceback (most recent call last):
  File "/usr/bin/hanga", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/hanga/scripts/client.py", line 368, in main
    HangaClient().run_command(arguments)
  File "/usr/lib/python2.7/site-packages/hanga/scripts/client.py", line 85, in run_command
    self._run_android_build(arguments)
  File "/usr/lib/python2.7/site-packages/hanga/scripts/client.py", line 106, in _run_android_build
    self.cloud_submit(args, filename)
  File "/usr/lib/python2.7/site-packages/hanga/scripts/client.py", line 179, in cloud_submit
    result = self._hangaapi.submit(args, filename, submit_callback)
  File "/usr/lib/python2.7/site-packages/hanga/api.py", line 68, in submit
    requests.post, "submit", data=fd, params=params, stream=True)
  File "/usr/lib/python2.7/site-packages/hanga/api.py", line 182, in _build_request
    r = method(url, headers=headers, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by kived** [comment]
It looks like the SSL certificate for hanga.io expired on April 18th.
